name: 'Get & cache dependencies'
description: 'An action to get and cache dependencies'
inputs:
  caching:
    description: 'Whether to cache dependencies'
    required: false
    default: 'true'
runs: 
  using: 'composite'
  steps:
  - name: Cache dependencies
    if: inputs.caching == 'true'
    id: cache
    uses: actions/cache@v3
    with:
      path: node_modules
      key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
  - name: Install dependencies
    if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
    run: npm ci
    shell: bash